# Navigation Links

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /#about
    weight: 20
  - name: Research
    url: /#research
    weight: 30
  - name: Projects
    url: /projects/
    weight: 40
  - name: Publications
    url: /publications/
    weight: 50
  - name: Awards
    url: /#awards
    weight: 60
  - name: Contact
    url: /#contact
    weight: 70
